// components/icons.tsx
import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  HelpCircle,
  ImageIcon,
  Info,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Building2,
  ShoppingBag,
  Users,
  BarChart,
  LogOut,
  Home,
  Package,
  DollarSign,
  Tag,
} from "lucide-react";

export const Icons = {
  logo: Command,
  close: X,
  check: Check,
  info: Info,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  shop: Building2,
  item: Package,
  employee: Users,
  dashboard: BarChart,
  logout: LogOut,
  home: Home,
  sales: DollarSign,
  tag: Tag,
  shoppingBag: ShoppingBag,
  image: ImageIcon,
  alertTriangle: AlertTriangle,
};